org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
systemProp.jdk.tls.client.protocols=TLSv1.2,TLSv1.3
systemProp.http.sslVerify=false
systemProp.https.sslVerify=false
kotlin.incremental=false
